name: PlatformIO upload package

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build-and-publish:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Download AVR GCC 15.2.0
        run: |
          curl -L "https://github.com/ZakKemble/avr-gcc-build/releases/download/v15.2.0-1/avr-gcc-15.2.0-x64-linux.tar.bz2" -o avr-gcc.tar.bz2
          mkdir -p avr-gcc
          tar -xf avr-gcc.tar.bz2 -C avr-gcc --strip-components=1
          
          cat << 'EOF' > avr-gcc/package.json
          {
            "name": "toolchain-atmelavr",
            "version": "15.2.0",
            "description": "Modern C++ using GCC Toolchain for Microchip AVR microcontrollers",
            "keywords": [
              "toolchain",
              "build tools",
              "compiler",
              "assembler",
              "linker",
              "preprocessor",
              "microchip",
              "avr",
              "c++20"
            ],
            "homepage": "https://gcc.gnu.org/wiki/avr-gcc",
            "license": "GPL-2.0-or-later",
            "system": [
              "linux_x86_64"
            ]
          }
          EOF

      - name: Build PlatformIO Project
        env:
          PIO_AVR_GCC_PATH: "symlink://${{ github.workspace }}/avr-gcc"
        run: pio run

      - name: Remove build artifacts before publish
        run: rm -rf .pio avr-gcc avr-gcc.tar.bz2 compile_commands.json

      - name: Verify package contents
        run: pio pkg pack

      - name: Login to PlatformIO
        run: pio account login -u ${{ secrets.PLATFORM_IO_USERNAME }} -p ${{ secrets.PLATFORM_IO_TOKEN }}

      - name: Publish PlatformIO package
        run: pio pkg publish --no-interactive --owner lordmax2

